---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Node.js and npm
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes

- name: Clone application repository
  git:
    repo: "https://github.com/Lukas-Bouhlel/task-management-system.git"
    dest: /home/lukasbouhlel/app/
    version: master
    force: yes
    update: yes
  become: false

- name: Install npm dependencies
  npm:
    path: /home/lukasbouhlel/app/

- name: Start the app with PM2
  shell: pm2 start npm --name "node-api" -- start
  args:
    chdir: /home/lukasbouhlel/app/
  register: pm2_start
  failed_when: pm2_start.rc != 0 and "Process already launched" not in pm2_start.stderr

- name: Save PM2 process list
  shell: pm2 save

- name: Generate PM2 startup script
  shell: pm2 startup systemd -u lukasbouhlel --hp /home/lukasbouhlel
