name: cd_workflow

on:
  workflow_run:
    workflows: ["ci_workflow"]
    types:
      - completed

jobs:
  deploy:
    if: >
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Configure SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH key presence
        run: |
          if [ ! -s ~/.ssh/id_rsa ]; then
            echo "❌ SSH private key is empty!"
            exit 1
          else
            echo "✅ SSH private key loaded."
            echo "SSH key size: $(wc -c < ~/.ssh/id_rsa) bytes"
          fi

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml -v